apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: flannel-public-ip-setter
  labels:
    app: flannel-public-ip-setter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flannel-public-ip-setter
  template:
    metadata:
      labels:
        app: flannel-public-ip-setter
    spec:
      serviceAccountName: flannel-ip-setter
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
      containers:
        - name: flannel-ip-setter
          image: "janeczku/rke-flannel-public-ip:0.0.3"
          command:
            - flannel-ip-setter
          ports:
            - containerPort: 2112
              name: metrics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel-ip-setter
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flannel-ip-setter-cr
  namespace: kube-system
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["nodes"]
    verbs: ["get", "watch", "list","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: kube-system
  name: flannel-ip-setter-crb
roleRef:
  kind: ClusterRole
  name: flannel-ip-setter-cr
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: flannel-ip-setter
    namespace: kube-system
